package keymgmt

import (
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"strings"

	"github.com/NubeIO/nubeio-rubix-lib-models-go/model"
)

// MetaKeyPendingKey holds the key staged during a provisioning/rotation window.
//
// The staged key is deliberately NOT written over Device.Manufacture: until the
// device has actually taken and saved the new key, its live key is still the old
// one. Overwriting immediately would cut contact with a device that had not been
// re-keyed yet (doc 08 section 8.2).
const MetaKeyPendingKey = "lora_pending_key"

// GenerateKey returns a fresh random AES-128 key from the OS CSPRNG.
//
// Keys are generated by Rubix CE rather than on-device: the CM4 has the best
// entropy source in the system (the STM32 firmware uses a hand-rolled LCG for
// its nonce and never enables its hardware RNG — doc 03 section 3.5), and generating
// here lets CE record the key atomically with the device identity.
func GenerateKey() (Key, error) {
	k := make([]byte, KeyLen)
	if _, err := rand.Read(k); err != nil {
		return nil, fmt.Errorf("keymgmt: generate key: %w", err)
	}
	return Key(k), nil
}

// GenerateKeyHex returns a fresh key as an uppercase hex string, the form the
// Device.Manufacture field and the device AT command both use.
func GenerateKeyHex() (string, error) {
	k, err := GenerateKey()
	if err != nil {
		return "", err
	}
	defer k.Zero()
	return strings.ToUpper(hex.EncodeToString(k)), nil
}

// Plan is the set of persistent changes a lifecycle transition requires. It is
// produced by pure functions so the state machine can be unit-tested without a
// database, then applied by the caller.
//
// Manufacture is empty when the device's live key must not change. A meta tag
// with an empty Value means "clear this tag".
type Plan struct {
	Manufacture string
	MetaTags    []*model.DeviceMetaTag
}

var errNilDevicePlan = errors.New("keymgmt: nil device")

// BeginProvision stages newKeyHex as the device's pending key and moves it to
// PENDING. The live key is left untouched so the device keeps working until it
// has actually taken the new key.
func BeginProvision(device *model.Device, newKeyHex string) (Plan, error) {
	if device == nil {
		return Plan{}, errNilDevicePlan
	}
	if _, err := decodeKey(newKeyHex, true); err != nil {
		return Plan{}, err
	}
	if state, ok := ParseProvisionState(metaTagValue(device, MetaKeyProvisionState)); ok && state == StateRetired {
		return Plan{}, errors.New("keymgmt: device is RETIRED; re-onboard it before provisioning")
	}
	return Plan{
		MetaTags: []*model.DeviceMetaTag{
			tag(MetaKeyPendingKey, strings.ToUpper(strings.TrimSpace(newKeyHex))),
			tag(MetaKeyProvisionState, string(StatePending)),
		},
	}, nil
}

// ConfirmProvision promotes the pending key to the live key: the device has
// proved it holds the new key (a frame decrypted and CMAC-verified under it).
func ConfirmProvision(device *model.Device) (Plan, error) {
	if device == nil {
		return Plan{}, errNilDevicePlan
	}
	pending := strings.ToUpper(strings.TrimSpace(metaTagValue(device, MetaKeyPendingKey)))
	if pending == "" {
		return Plan{}, errors.New("keymgmt: no pending key to confirm")
	}
	if _, err := decodeKey(pending, true); err != nil {
		return Plan{}, fmt.Errorf("keymgmt: stored pending key is unusable: %w", err)
	}
	return Plan{
		Manufacture: pending,
		MetaTags: []*model.DeviceMetaTag{
			tag(MetaKeyPendingKey, ""), // clear: a used key must not linger
			tag(MetaKeyProvisionState, string(StateActive)),
			tag(MetaKeyMode, string(ModePerDeviceKey)),
		},
	}, nil
}

// AbortProvision drops the staged key and returns the device to its previous
// state. Used when the operator cancels, or an install could not be verified.
func AbortProvision(device *model.Device) (Plan, error) {
	if device == nil {
		return Plan{}, errNilDevicePlan
	}
	// A device that already had its own key falls back to ACTIVE; one that
	// never did returns to UNPROVISIONED.
	prev := StateUnprovisioned
	if device.Manufacture != "" {
		prev = StateActive
	}
	return Plan{
		MetaTags: []*model.DeviceMetaTag{
			tag(MetaKeyPendingKey, ""),
			tag(MetaKeyProvisionState, string(prev)),
		},
	}, nil
}

// RetireDevice tombstones a device: its key is withdrawn and the address is
// marked so it is not silently re-onboarded (doc 08 section 8.3).
//
// Manufacture is intentionally left alone: the caller decides whether to clear
// the stored key outright or keep it briefly to decode traffic already in
// flight. The RETIRED state is what stops the device being treated as live.
func RetireDevice(device *model.Device) (Plan, error) {
	if device == nil {
		return Plan{}, errNilDevicePlan
	}
	return Plan{
		MetaTags: []*model.DeviceMetaTag{
			tag(MetaKeyPendingKey, ""),
			tag(MetaKeyProvisionState, string(StateRetired)),
		},
	}, nil
}

func tag(key, value string) *model.DeviceMetaTag {
	return &model.DeviceMetaTag{Key: key, Value: value}
}
