name: build-release

on:
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
    branches:
      - main
      - master
      - develop
  push:
    branches:
      - main
      - master
      - develop
    tags:
      - 'v*'

env:
  APP_NAME: module-core-loraraw
  GHCR_IMAGE: ghcr.io/nubeio/module-core-loraraw
  PLATFORMS: linux/amd64

jobs:

  context:
    runs-on: ubuntu-22.04

    outputs:
      shouldBuild: ${{ steps.context.outputs.decision_build }}
      shouldPublish: ${{ steps.context.outputs.decision_publish }}
      isRelease: ${{ steps.context.outputs.isTag }}
      afterRelease: ${{ steps.context.outputs.isAfterMergedReleasePR }}
      sha: ${{ steps.context.outputs.commitId }}
      version: ${{ steps.context.outputs.version }}
      shortCommitId: ${{ steps.context.outputs.shortCommitId }}
      fqn: ${{ env.APP_NAME }}-${{ steps.context.outputs.version }}-${{ steps.context.outputs.shortCommitId }}

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.NUBEIO_CI_GITHUBPROJECT_TOKEN }}

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          git-user-signingkey: true
          git-commit-gpgsign: true
          git-tag-gpgsign: true
          git-push-gpgsign: false
          gpg-private-key: ${{ secrets.NUBEIO_CI_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.NUBEIO_CI_GPG_PASSPHARSE }}

      - name: Project context
        id: context
        uses: zero88/gh-project-context@v1
        with:
          dry: false
          defaultBranch: master

  build:
    runs-on: ubuntu-22.04
    needs: context
    if: needs.context.outputs.shouldBuild == 'true'
    env:
      GITHUB_TOKEN: ${{ secrets.NUBEIO_CI_GITHUBPROJECT_TOKEN }}
    services:
      registry:
        image: zero88/gh-registry:latest
        ports:
          - 5000:5000
        options: >-
          -v /home/runner:/var/lib/registry
          --name registry
    steps:
      - uses: actions/checkout@v4

      - name: Set current date as env variable
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"

      - name: Build inside Docker
        run: |
          docker build \
          -f Dockerfile \
          -t build-image .

          container_id=$(docker create build-image)
          docker cp $container_id:/app/module-core-loraraw-amd64 ./module-core-loraraw-amd64
          docker cp $container_id:/app/module-core-loraraw-armv7 ./module-core-loraraw-armv7
          docker rm $container_id

      - name: Zip artifacts
        if: ${{ needs.context.outputs.isRelease == 'true' }}
        run: |
          mkdir -p /tmp/zip
          artifact=${{ needs.context.outputs.fqn }}.armv7
          zip -r /tmp/zip/$artifact.zip ./module-core-loraraw-armv7
          artifact=${{ needs.context.outputs.fqn }}.amd64
          zip -r /tmp/zip/$artifact.zip ./module-core-loraraw-amd64

      - name: Create Release
        if: ${{ needs.context.outputs.isRelease == 'true' }}
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.context.outputs.version }}
          name: Release v${{ needs.context.outputs.version }}
          draft: false
          prerelease: false
          files: |
            /tmp/zip/*.amd64.zip
            /tmp/zip/*.armv7.zip
